apiVersion: v1
kind: PersistentVolume # Create a PV
metadata:
  name: app-pv # Sets PV's name
  labels:
    app: wordpress # Sets PV's type to local
spec:
  storageClassName: standard
  capacity:
    storage: 20Gi # Sets PV Volume
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/mysql" # Sets the volume's path